fix(profile):Fix Dividing components | JIRA PT-201
ltv/argon-dashboard-vue3 pull request #124
Opened 2022-07-01 08:50 UTC by Trung-Hieu-Dev

2022-07-03 06:39 UTC, dzunglee requested changes

2022-07-03 06:39 UTC, dzunglee commented on src/modules/profile/views/components/UserCard.vue
> +<template>
Sử dụng user card này bốc qua bên user profile dùng luôn nha anh, để nó duplicate với bên đó

2022-07-04 01:48 UTC, Trung-Hieu-Dev commented on src/modules/profile/views/components/UserCard.vue
> +<template>
Ok em

2022-07-04 04:42 UTC, dzunglee approved these changes

2022-07-04 04:43 UTC, merged